theme = "catppuccin_mocha"

[editor]
mouse = false
bufferline = "never"
line-number = "relative"
shell = ["zsh", "-c"]
cursorline = true
auto-save = true
color-modes = true

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "separator", "position", "total-line-numbers", "position-percentage", "file-encoding"]
mode.normal = "Normal"
mode.insert = "Insert"
mode.select = "Select"

[editor.indent-guides]
render = true
character = "┊"

[keys.normal."C-f"]
i = ":toggle file-picker.git-ignore"
h = ":toggle lsp.display-inlay-hints"
r = ":reload-all"



